---
abstract: 'Object-oriented access to hash with multi-valued simple (non-reference) elements'
author:
  - 'Nat Goodman <natg@shore.net>'
build_requires:
  Exporter: 0
  Test::Deep: 0
  Test::More: 0.88
configure_requires:
  Module::Build: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Hash-AutoHash-AVPairsMulti
provides:
  Hash::AutoHash::AVPairsMulti:
    file: lib/Hash/AutoHash/AVPairsMulti.pm
    version: 1.14
  Hash::AutoHash::AVPairsMulti::helper:
    file: lib/Hash/AutoHash/AVPairsMulti.pm
    version: 0
  Hash::AutoHash::AVPairsMulti::tie:
    file: lib/Hash/AutoHash/AVPairsMulti.pm
    version: 0
requires:
  Carp: 0
  Hash::AutoHash: 1.15
  Hash::AutoHash::MultiValued: 1.14
resources:
  license: http://dev.perl.org/licenses/
version: 1.14
